border_width = 2
margin = 4
workspace_margin = 4
# default_width = 1280
# default_height = 720
# always_float = false
default_border_color = "#bd93f9"
floating_border_color = "#bd93f9"
focused_border_color = "#ff79c6"
